- name: Run kolla-ansible
  raw: "{{ item }}"
  with_items:
    - kolla-ansible -i /etc/kolla/all-in-one bootstrap-servers
    - kolla-ansible -i /etc/kolla/all-in-one prechecks
    - kolla-ansible -i /etc/kolla/all-in-one deploy
    - kolla-ansible -i /etc/kolla/all-in-one post-deploy
