---

- name: Install kolla with stein version, ansible and python-openstack via pip
  become: yes
  pip:
    name:
    - kolla-ansible==8.0.0
    - ansible
    - python-openstackclient
    executable: pip3

- name: Setup kolla etc directory
  become: yes
  file:
    path: /etc/kolla/
    state: directory
    mode: '0755'

- name: Copy template setup files, passwords
  become: yes
  copy:
    src: /usr/local/share/kolla-ansible/etc_examples/kolla/passwords.yml
    dest: /etc/kolla/
    remote_src: yes

- name: Copy template setup files, inventories
  become: yes
  copy:
    src: /usr/local/share/kolla-ansible/ansible/inventory/all-in-one
    dest: /etc/kolla/
    remote_src: yes

- name: Copy template setup files, globals modified
  become: yes
  copy:
    src: ./templates/globals.yml 
    dest: /etc/kolla/
    remote_src: yes

- name: Generate passwords
  become: yes
  raw: kolla-genpwd

- name: Disable host key checking globally for ansible
  become: yes
  template:
    backup: no
    src: ./templates/ansible.cfg
    dest: "/etc/ansible/ansible.cfg"
