---

- name: Install kolla with stein version, ansible and python-openstack via pip
  become: yes
  pip:
    name:
    - kolla-ansible=8.0.0
    - ansible
    - python-openstackclient

- name: Setup kolla etc directory
  become: yes
  file:
    path: /etc/kolla/
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Copy template setup files: passwords
  become: yes
  copy:
    src: cp -r /usr/local/share/kolla-ansible/etc_examples/kolla/passwords
    dest: /etc/kolla/
    remote_src: yes

- name: Copy template setup files: inventories
  become: yes
  copy:
    src: cp /usr/local/share/kolla-ansible/ansible/inventory/
    dest: /etc/kolla/
    remote_src: yes

- name: Copy template setup files: globals modified
  become: yes
  copy:
    src: cp -r /home/tfm/Desktop/repo/Kolla_Automation/templates/globals.yml 
    dest: /etc/kolla/
    remote_src: yes

- name: Generate passwords
  become: yes
  raw: kolla-genpwd

- name: Disable host key checking globally for ansible
  template:
    backup: no
    src: ./templates/ansible.cfg
    dest: "/etc/ansible/ansible.cfg"
