---

- name: Install kolla with stein version, ansible and python-openstack via pip
  become: yes
  pip:
    name:
    - kolla-ansible=8.0.0
    - ansible
    - python-openstackclient

- name: Setup kolla etc directory
  become: yes
  file:
    path: /etc/kolla/
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  when: inventory_hostname in groups['provisioner']

- name: Copy template setup files
  become: yes
  copy:
    src: /usr/local/share/kolla-ansible/etc_examples/kolla/
    dest: /etc/kolla/
    remote_src: yes
  when: inventory_hostname in groups['provisioner']

- name: Generate passwords
  become: yes
  raw: kolla-genpwd
  when: inventory_hostname in groups['provisioner']

- name: Ensure SSH config file is present
  file:
    path: "/home/{{ ansible_user }}/.ssh"
    state: directory
    mode: '0755'
  when: inventory_hostname in groups['provisioner']

- name: Upload SSH config file
  template:
    backup: no
    src: config.j2
    dest: "/home/{{ ansible_user }}/.ssh/config"
  when: inventory_hostname in groups['provisioner']

- name: Ensure ansible rc dir is present
  file:
    path: "/etc/ansible"
    state: directory
    mode: '0755'
  when: inventory_hostname in groups['provisioner']

- name: Disable host key checking globally for ansible
  template:
    backup: no
    src: ansible.cfg.j2
    dest: "/etc/ansible/ansible.cfg"
  when: inventory_hostname in groups['provisioner']
